"""
Django settings for my_stock_view project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a%^vfq%up=vzu$m27-7hwy1y5!-47^pz2z8r*sv^#!=%duf#0u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mathfilters',
    # custom apps
    'catalog.apps.CatalogConfig',
    'account.apps.AccountConfig',
    'crawler.apps.CrawlerConfig',
    # django-q
    'django_q',
    # django-crontab
    'django_crontab',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_stock_view.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./template/','catalog/template/','./templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries' :   {
                'pagination_tags'   :   'catalog.templatetags.pagination_tags',
                'get_tuple_tags'    :   'catalog.templatetags.get_tuple_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'my_stock_view.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


USE_I18N = True

USE_L10N = True

USE_TZ = True

TIME_ZONE = 'Asia/Taipei'

DATETIME_FORMAT = ("%m/%d/%Y %H:%M:%S",)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = f'{BASE_DIR}/catalog/static/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

Q_CLUSTER = {
    'name'      :   'crawlerORM',
    'workers'   :   1,
    'timeout'   :   7200,
    'retry'     :   7260,
    'orm'       :   'default',

    
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRONJOBS = [
    ('*/2 9-14 * * 1-5', 'crawler.scripts.crawler_functions.get_stock_cur_price'),
    ('*/60 14 * * 1-5','crawler.scripts.crawler_functions.update_exist_stock_hp_sum'),
    ('*/60 9-14 * * 1-5', 'crawler.scripts.news_crawler.get_news'),
    ('*/60 15 1 * *', 'crawler.scripts.db_control.news_ctrl'),
    ('*/60 15 1 * *', 'crawler.scripts.db_control.hp_ctrl'),
    ('*/60 15 1 * *', 'crawler.scripts.db_control.hp_sum_ctrl'),
     
            ]
