# Generated by Django 3.1.2 on 2022-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinformation',
            name='market_value',
            field=models.BigIntegerField(blank=True, help_text='Enter the market value of the corps', null=True),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='revenue',
            field=models.BigIntegerField(blank=True, max_length=18, null=True),
        ),
    ]
