# Generated by Django 3.1.2 on 2022-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220405_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Enter the title of the news', max_length=80),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
