# Generated by Django 3.1.2 on 2022-03-27 00:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_usersubscriptionlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscriptionList',
            new_name='SubList',
        ),
    ]
