# Generated by Django 3.1.2 on 2022-04-10 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20220410_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLineID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.TextField(blank=True, default=True, max_length=20)),
                ('activate', models.BooleanField(default=True)),
                ('pushNews', models.BooleanField(default=True)),
                ('pushPrice', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
