# Generated by Django 3.1.2 on 2022-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220410_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlineid',
            name='line_id',
            field=models.TextField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
