# Generated by Django 3.1.2 on 2022-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220412_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='related_stock',
            field=models.ManyToManyField(blank=True, to='catalog.Stock'),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sublist',
            name='stock_list',
            field=models.ManyToManyField(blank=True, to='catalog.Stock'),
        ),
        migrations.AlterField(
            model_name='userlineid',
            name='line_id',
            field=models.CharField(blank=True, default=None, max_length=63, null=True),
        ),
    ]
