# Generated by Django 3.1.2 on 2022-04-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220415_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Enter the title of the news', max_length=128),
        ),
    ]
